### ISSUE TITLE
Error with 1.7.1 in Pulumi App Deploy

### ISSUE THREAD

**Issue by brentshulman-silkline** [pulumi/pulumi-std#65]
### What happened?

Deploys of our stack in `app.pulumi.com` started failing out of the blue yesterday with errors originating from the 1.7.1 release of this library

### Example

![image](https://github.com/pulumi/pulumi-std/assets/134343004/4f17fad9-5b1e-4d80-b7ac-5c3a44d2d7a6)

### Output of `pulumi about`

-

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Sorry for the trouble and thanks for opening the issue!

Looks like a side effect of switching to cross-building the release on Ubuntu rather than on macOS means that CGO is now enabled, which is not what we want and is the root cause of this problem. We'll have to explicitly disable that via `CGO_ENABLED=0`. Working on a fix

**Comment by justinvp** [comment]
This should now be fixed in [v1.7.2](https://github.com/pulumi/pulumi-std/releases/tag/v1.7.2).
